apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-container
        image: acr0510.azurecr.io/spring-image-acr:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr0510PullImage
