apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  annotations: 
    kubernetes.io/ingress.class: traefik
  name: kubercloud-ingress
  namespace: kubernetes-demo
spec: 
  rules: 
    - host: mysbapp.snicloud.xyz
      http: 
        paths: 
          - backend: 
              service:
                name: kubercloud-service
                port: 
                  number: 80
            path: /
            pathType: Prefix
-----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-container
        image: acr0510.azurecr.io/spring-image-acr:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr0510pullimage
